### ISSUE TITLE
Set 'worker_processes: 1' in nginx.conf

### ISSUE THREAD

**Issue by lyuich** [rozarioshovon/mcon#1]
### Write a summary of this issue

- Increase the efficiency of 'keepalive' because the competition server has only 2 cores

### List the details of what to do as a list

- [ ] Set `worker_processes` from 4 to 1 in nginx.conf

```text
$ grep processor /proc/cpuinfo
processor       : 0
processor       : 1
```

### Any references (Describe URL of documents or webpages)

- none

**Comment by lyuich** [comment]
```text

**Comment by ghost** [comment]
I was changed.
